module.exports = function(_this){
    return{
        getPercentage:{
            method:'GET',
            urlData:{
                fid:_this._getProp('formId'),
                matchid:_this._getProp('matchid'),
                winnerid:_this._getProp('winnerid'),
            }
        },
        getForm:{
            method:'GET',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        getAllSubmissionByField:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        getAllSubmission:{
            method:'GET',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        getSubmissionBySid:{
            method:'GET',
            urlData:{
                fid:_this._getProp('formId'),
                sid:_this._getProp('sid')
            }
        },
        addSubmission:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        editSubmission:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
                sid:_this._getProp('sid')
            }
        },
        addSubmissionWithoutOpenId:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        addSubmissionLimitByOneField:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        addSubmissionWithoutOpenIdByOneField:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
            }
        },
        addSubmissionWithoutOpenIdByCrmTel:{
            method:'POST',
            urlData:{
                fid:_this._getProp('formId'),
            }
        }
    };
};
